### ISSUE TITLE
New module scaffolding still using iles ^0.5

### ISSUE THREAD

**Issue by TechAkayy** [ElMassimo/create-iles-module#2]
Both next & latest tags are still pointing to iles^0.5. So, any new iles module, created via this, when used, ends up throwing peer dependencies issues. There is an incorrect tag **lastest**. 

Usage (`npm init iles-module@next`) on this package's readme is pointing to next tag, so fixing only latest might still be having issues. 

![image](https://user-images.githubusercontent.com/73772701/230900761-cf8788e1-a390-45c6-9ddb-c7ef2969407d.png)

**Comment by ElMassimo** [comment]
Thanks for the reminder!

`lastest` was a typo in my release script, fixed!
